services:
  shell:
    build: .
    volumes:
      - .:/root/.dotfiles
    stdin_open: true
    tty: true

  bench-zsh:
    build: .
    volumes:
      - .:/root/.dotfiles
    command: ["bench-startup", "--target", "zsh", "--threshold", "300"]

  bench-nvim:
    build: .
    volumes:
      - .:/root/.dotfiles
    command: ["bench-startup", "--target", "nvim", "--threshold", "500"]

  nvim:
    build: .
    volumes:
      - .:/root/.dotfiles
      - nvim-data:/root/.local/share/nvim
    stdin_open: true
    tty: true
    command: ["nvim"]

volumes:
  nvim-data:
