services:
  shell:
    build: .
    volumes:
      - .:/root/.dotfiles
    stdin_open: true
    tty: true

  bench:
    build: .
    volumes:
      - .:/root/.dotfiles
    command: ["bench-startup", "--threshold", "200"]
